"""add catalog fields, valuations, image captions and unit preference

Revision ID: 0cfa5f224cf3
Revises: 34fcd61c94a9
Create Date: 2026-09-27 14:14:54.515264

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cfa5f224cf3"
down_revision: str | Sequence[str] | None = "34fcd61c94a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "valuations",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("item_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("valued_on", sa.String(length=10), nullable=True),
        sa.Column("appraiser", sa.String(length=200), nullable=True),
        sa.Column("valuation_type", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_valuations_item_id"), "valuations", ["item_id"], unique=False)
    op.add_column("images", sa.Column("width", sa.Integer(), nullable=True))
    op.add_column("images", sa.Column("height", sa.Integer(), nullable=True))
    op.add_column("images", sa.Column("caption", sa.String(length=500), nullable=True))
    op.add_column("images", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("items", sa.Column("reference_number", sa.String(length=100), nullable=True))
    op.add_column("items", sa.Column("acquisition_method", sa.String(length=20), nullable=True))
    op.add_column("items", sa.Column("acquisition_place", sa.String(length=200), nullable=True))
    op.add_column("items", sa.Column("length_cm", sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column(
        "items", sa.Column("diameter_cm", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    # A date becomes its ISO text; from here it may also be just a year or a month.
    op.alter_column(
        "items",
        "acquisition_date",
        existing_type=sa.DATE(),
        type_=sa.String(length=10),
        existing_nullable=True,
        postgresql_using="to_char(acquisition_date, 'YYYY-MM-DD')",
    )
    op.add_column(
        "user",
        sa.Column("preferred_units", sa.String(length=10), server_default="metric", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "preferred_units")
    # Lossy by necessity: a year or a month becomes its first day.
    op.alter_column(
        "items",
        "acquisition_date",
        existing_type=sa.String(length=10),
        type_=sa.DATE(),
        existing_nullable=True,
        postgresql_using=(
            "to_date(CASE length(acquisition_date)"
            " WHEN 4 THEN acquisition_date || '-01-01'"
            " WHEN 7 THEN acquisition_date || '-01'"
            " ELSE acquisition_date END, 'YYYY-MM-DD')"
        ),
    )
    op.drop_column("items", "diameter_cm")
    op.drop_column("items", "length_cm")
    op.drop_column("items", "acquisition_place")
    op.drop_column("items", "acquisition_method")
    op.drop_column("items", "reference_number")
    op.drop_column("images", "description")
    op.drop_column("images", "caption")
    op.drop_column("images", "height")
    op.drop_column("images", "width")
    op.drop_index(op.f("ix_valuations_item_id"), table_name="valuations")
    op.drop_table("valuations")
    # ### end Alembic commands ###
