"""add import entries and photos

Revision ID: 127b6cf7dd32
Revises: 10c2acea8a2d
Create Date: 2026-09-27 18:48:26.247740

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "127b6cf7dd32"
down_revision: str | Sequence[str] | None = "10c2acea8a2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_entries",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("import_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("item_id", sa.UUID(as_uuid=False), nullable=True),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_id", "external_id"),
    )
    op.create_index(
        op.f("ix_import_entries_import_id"), "import_entries", ["import_id"], unique=False
    )
    op.create_index(op.f("ix_import_entries_item_id"), "import_entries", ["item_id"], unique=False)
    op.create_table(
        "import_photos",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("import_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("item_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("mark_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("caption", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("image_id", sa.UUID(as_uuid=False), nullable=True),
        sa.ForeignKeyConstraint(["image_id"], ["images.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["import_id"], ["imports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["mark_id"], ["marks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_id", "filename"),
    )
    op.create_index(
        op.f("ix_import_photos_import_id"), "import_photos", ["import_id"], unique=False
    )
    op.add_column("imports", sa.Column("options", sa.JSON(), nullable=True))
    op.add_column("imports", sa.Column("created_collection_ids", sa.JSON(), nullable=True))
    op.add_column("imports", sa.Column("created_tag_ids", sa.JSON(), nullable=True))
    op.add_column("imports", sa.Column("outcome", sa.JSON(), nullable=True))
    op.add_column("imports", sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("imports", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("imports", "completed_at")
    op.drop_column("imports", "committed_at")
    op.drop_column("imports", "outcome")
    op.drop_column("imports", "created_tag_ids")
    op.drop_column("imports", "created_collection_ids")
    op.drop_column("imports", "options")
    op.drop_index(op.f("ix_import_photos_import_id"), table_name="import_photos")
    op.drop_table("import_photos")
    op.drop_index(op.f("ix_import_entries_item_id"), table_name="import_entries")
    op.drop_index(op.f("ix_import_entries_import_id"), table_name="import_entries")
    op.drop_table("import_entries")
    # ### end Alembic commands ###
