"""add images table

Revision ID: 34fcd61c94a9
Revises: 62a67799efe0
Create Date: 2026-02-04 16:55:08.313105

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34fcd61c94a9"
down_revision: str | Sequence[str] | None = "62a67799efe0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("item_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("mark_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(item_id IS NOT NULL AND mark_id IS NULL) OR (item_id IS NULL AND mark_id IS NOT NULL)",
            name="ck_images_exactly_one_parent",
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mark_id"], ["marks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(op.f("ix_images_item_id"), "images", ["item_id"], unique=False)
    op.create_index(op.f("ix_images_mark_id"), "images", ["mark_id"], unique=False)
    op.create_index(op.f("ix_images_user_id"), "images", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_images_user_id"), table_name="images")
    op.drop_index(op.f("ix_images_mark_id"), table_name="images")
    op.drop_index(op.f("ix_images_item_id"), table_name="images")
    op.drop_table("images")
    # ### end Alembic commands ###
