"""replace categories with tags

Revision ID: 3a48256b3cb5
Revises: d4e4fa6bb67b
Create Date: 2026-02-03 17:48:56.798423

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a48256b3cb5"
down_revision: str | Sequence[str] | None = "d4e4fa6bb67b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_tags_user_name"),
    )
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "item_tags",
        sa.Column("item_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("tag_id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("item_id", "tag_id"),
    )
    op.drop_index(op.f("ix_items_category"), table_name="items")
    op.drop_index(op.f("ix_items_user_category"), table_name="items")
    op.drop_column("items", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("category", sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.create_index(op.f("ix_items_user_category"), "items", ["user_id", "category"], unique=False)
    op.create_index(op.f("ix_items_category"), "items", ["category"], unique=False)
    op.drop_table("item_tags")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
