"""add marks provenance_entries item_notes and acquisition_source

Revision ID: 4a2e0ae568cc
Revises: 3a48256b3cb5
Create Date: 2026-02-03 19:22:26.003553

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a2e0ae568cc"
down_revision: str | Sequence[str] | None = "3a48256b3cb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_notes",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("item_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_notes_item_id"), "item_notes", ["item_id"], unique=False)
    op.create_table(
        "marks",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("item_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_marks_item_id"), "marks", ["item_id"], unique=False)
    op.create_table(
        "provenance_entries",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("item_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("owner_name", sa.String(length=200), nullable=False),
        sa.Column("date_from", sa.String(length=100), nullable=True),
        sa.Column("date_to", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provenance_entries_item_id"), "provenance_entries", ["item_id"], unique=False
    )
    op.add_column("items", sa.Column("acquisition_source", sa.String(length=200), nullable=True))
    op.drop_column("items", "provenance_notes")
    op.drop_column("items", "notes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "items", sa.Column("provenance_notes", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("items", "acquisition_source")
    op.drop_index(op.f("ix_provenance_entries_item_id"), table_name="provenance_entries")
    op.drop_table("provenance_entries")
    op.drop_index(op.f("ix_marks_item_id"), table_name="marks")
    op.drop_table("marks")
    op.drop_index(op.f("ix_item_notes_item_id"), table_name="item_notes")
    op.drop_table("item_notes")
    # ### end Alembic commands ###
