"""add collection type and item type_fields

Revision ID: 62a67799efe0
Revises: 4a2e0ae568cc
Create Date: 2026-02-03 22:10:30.015173

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62a67799efe0"
down_revision: str | Sequence[str] | None = "4a2e0ae568cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collections",
        sa.Column("type", sa.String(length=50), nullable=False, server_default="general"),
    )
    op.add_column("items", sa.Column("type_fields", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "type_fields")
    op.drop_column("collections", "type")
    # ### end Alembic commands ###
